# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]       
 set_property IOSTANDARD LVCMOS33 [get_ports clk]
 create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
#seven-segment LED display
set_property PACKAGE_PIN V7 [get_ports {LED_out[7]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[7]}]
set_property PACKAGE_PIN W7 [get_ports {LED_out[6]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[6]}]
set_property PACKAGE_PIN W6 [get_ports {LED_out[5]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[5]}]
set_property PACKAGE_PIN U8 [get_ports {LED_out[4]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[4]}]
set_property PACKAGE_PIN V8 [get_ports {LED_out[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {LED_out[2]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[2]}]
set_property PACKAGE_PIN V5 [get_ports {LED_out[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[1]}]
set_property PACKAGE_PIN U7 [get_ports {LED_out[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[0]}]
set_property PACKAGE_PIN U2 [get_ports {Anode_Activate[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[0]}]
set_property PACKAGE_PIN U4 [get_ports {Anode_Activate[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[1]}]
set_property PACKAGE_PIN V4 [get_ports {Anode_Activate[2]}]               
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[2]}]
set_property PACKAGE_PIN W4 [get_ports {Anode_Activate[3]}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[3]}]
set_property PACKAGE_PIN W19 [get_ports {quarterBtn}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {quarterBtn}]
set_property PACKAGE_PIN U18 [get_ports {dollarBtn}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {dollarBtn}]
set_property PACKAGE_PIN T17 [get_ports {cardBtn}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {cardBtn}]
set_property PACKAGE_PIN T18 [get_ports {changeBtn}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {changeBtn}]
   set_property PACKAGE_PIN U17 [get_ports {buyBtn}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {buyBtn}]
   
#Despensing
set_property PACKAGE_PIN L1 [get_ports {Despensing[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Despensing[0]}]
set_property PACKAGE_PIN P1 [get_ports {Despensing[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Despensing[1]}]
set_property PACKAGE_PIN N3 [get_ports {Despensing[2]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Despensing[2]}]
set_property PACKAGE_PIN P3 [get_ports {Despensing[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Despensing[3]}]
set_property PACKAGE_PIN U3 [get_ports {Despensing[4]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Despensing[4]}]
set_property PACKAGE_PIN W3 [get_ports {Despensing[5]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Despensing[5]}]
   
#Selection
set_property PACKAGE_PIN R2 [get_ports {Selection[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Selection[0]}]
set_property PACKAGE_PIN T1 [get_ports {Selection[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Selection[1]}]
set_property PACKAGE_PIN U1 [get_ports {Selection[2]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Selection[2]}]
set_property PACKAGE_PIN W2 [get_ports {Selection[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Selection[3]}]
set_property PACKAGE_PIN R3 [get_ports {Selection[4]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Selection[4]}]
set_property PACKAGE_PIN T2 [get_ports {Selection[5]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Selection[5]}]
set_property PACKAGE_PIN T3 [get_ports {Selection[6]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Selection[6]}]
set_property PACKAGE_PIN V2 [get_ports {Selection[7]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Selection[7]}]