## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]


set_property IOSTANDARD LVCMOS33 [get_ports {OutsideSelectedFloor[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutsideSelectedFloor[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutsideSelectedFloor[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutsideSelectedFloor[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DirectionState[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DirectionState[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DirectionState[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DirectionState[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {InsideDesiredFloor[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {InsideDesiredFloor[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {InsideDesiredFloor[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {InsideDesiredFloor[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {InsideDesiredFloor[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutsideLEDDebug[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutsideLEDDebug[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutsideLEDDebug[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutsideLEDDebug[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutsideLEDDebug[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {InsideLEDDebug[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {InsideLEDDebug[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {InsideLEDDebug[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {InsideLEDDebug[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {InsideLEDDebug[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports update]
set_property PACKAGE_PIN R3 [get_ports {InsideDesiredFloor[4]}]
set_property PACKAGE_PIN W2 [get_ports {InsideDesiredFloor[3]}]
set_property PACKAGE_PIN U1 [get_ports {InsideDesiredFloor[2]}]
set_property PACKAGE_PIN T1 [get_ports {InsideDesiredFloor[1]}]
set_property PACKAGE_PIN R2 [get_ports {InsideDesiredFloor[0]}]
set_property PACKAGE_PIN V2 [get_ports {OutsideSelectedFloor[2]}]
set_property PACKAGE_PIN T3 [get_ports {OutsideSelectedFloor[1]}]
set_property PACKAGE_PIN T2 [get_ports {OutsideSelectedFloor[0]}]
set_property PACKAGE_PIN W13 [get_ports {OutsideSelectedFloor[3]}]
set_property PACKAGE_PIN L1 [get_ports {DirectionState[0]}]
set_property PACKAGE_PIN P1 [get_ports {DirectionState[1]}]
set_property PACKAGE_PIN N3 [get_ports {DirectionState[2]}]
set_property PACKAGE_PIN P3 [get_ports {DirectionState[3]}]
set_property PACKAGE_PIN W19 [get_ports {update}]
set_property PACKAGE_PIN U16 [get_ports {OutsideLEDDebug[4]}]
set_property PACKAGE_PIN E19 [get_ports {OutsideLEDDebug[3]}]
set_property PACKAGE_PIN U19 [get_ports {OutsideLEDDebug[2]}]
set_property PACKAGE_PIN V19 [get_ports {OutsideLEDDebug[1]}]
set_property PACKAGE_PIN W18 [get_ports {OutsideLEDDebug[0]}]
set_property PACKAGE_PIN U14 [get_ports {InsideLEDDebug[4]}]
set_property PACKAGE_PIN V14 [get_ports {InsideLEDDebug[3]}]
set_property PACKAGE_PIN V13 [get_ports {InsideLEDDebug[2]}]
set_property PACKAGE_PIN V3 [get_ports {InsideLEDDebug[1]}]
set_property PACKAGE_PIN W3 [get_ports {InsideLEDDebug[0]}]

set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN W15 [get_ports down]
set_property PACKAGE_PIN W14 [get_ports up]

#7 segment display
set_property PACKAGE_PIN W7 [get_ports {DisplayFloor[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DisplayFloor[6]}]
set_property PACKAGE_PIN W6 [get_ports {DisplayFloor[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DisplayFloor[5]}]
set_property PACKAGE_PIN U8 [get_ports {DisplayFloor[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DisplayFloor[4]}]
set_property PACKAGE_PIN V8 [get_ports {DisplayFloor[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DisplayFloor[3]}]
set_property PACKAGE_PIN U5 [get_ports {DisplayFloor[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DisplayFloor[2]}]
set_property PACKAGE_PIN V5 [get_ports {DisplayFloor[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DisplayFloor[1]}]
set_property PACKAGE_PIN U7 [get_ports {DisplayFloor[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DisplayFloor[0]}]

#set_property PACKAGE_PIN V7 [get_ports dp]							
#	set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN U2 [get_ports {Anode_Activate[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[0]}]
set_property PACKAGE_PIN U4 [get_ports {Anode_Activate[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[1]}]
set_property PACKAGE_PIN V4 [get_ports {Anode_Activate[2]}]               
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[2]}]
set_property PACKAGE_PIN W4 [get_ports {Anode_Activate[3]}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[3]}]
